version: '3.8'
services:
  postgres:
    image: 'postgres:14.5'
    container_name: pediTrack_postgres
    volumes:
      - pedi_track_pgdata:/var/lib/postgresql/data
    ports:
      - 8080:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pediTrack
      pull_policy: always
volumes:
  pedi_track_pgdata:
networks:
  default:
    name: pedi_track