version: '3.8'
services:
  peditrack-db:
    image: 'postgres:14.5'
    container_name: pediTrack_postgres
    volumes:
      - peditrack_pgdata:/var/lib/postgresql/data
    ports:
      - '5435:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: peditrack
    pull_policy: always
volumes:
  peditrack_pgdata:
networks:
  default:
    name: peditrack