server:
  port: 8085
  error:
    whitelabel:
      enabled: false
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8185
spring:
  profiles:
    active:
  application:
    name: peditrack
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        order_by:
          default_null_ordering: last
          types:
            print:
              banner: false
        format_sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/peditrack
    username: postgres
    password: postgres
    hikari:
      pool-name: peditrack
      register-mbeans: true
      maximum-pool-size: 8
  flyway:
    baselineOnMigrate: true
    locations:
      - classpath:/db/migration
  sql:
    init:
      platform: postgresql
logging:
  level:
    root: INFO
    web: DEBUG

