server:
  port: 8085
  error:
    whitelabel:
      enabled: false
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8185
spring:
  main:
    allow-circular-references: true
  profiles:
    active: dev
  application:
    name: pedimed
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        order_by:
          default_null_ordering: last
          types:
            print:
              banner: false
        format_sql: false
    hikari:
      pool-name: pedimed
      register-mbeans: true
      maximum-pool-size: 8
  flyway:
    baselineOnMigrate: true
    locations:
      - classpath:/db/migration
    enabled : true
  sql:
    init:
      platform: postgresql
logging:
  level:
    root: info
    web: info
    tomcat: info
    hibernate: info
    org.springframework.orm.jpa: debug
    org.hibernate: debug
jwt:
  secret: mySecretKey
  expirationMs: 28000000

---
#################################################################
#                              DEV                              #
#################################################################
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: pedimed-dev
  flyway:
    user: postgres
    password: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/pedimed
    username: postgres
    password: postgres
    hikari:
      pool-name: pedimed
      register-mbeans: true
      maximum-pool-size: 8
  jpa:
    show-sql: true

logging:
  level:
    root: info
---
#################################################################
#                              PROD                             #
#################################################################
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: pedimed
  flyway:
    user: postgres
    password: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pedimed
    username: postgres
    password: postgres
    hikari:
      pool-name: pedimed
      register-mbeans: true
      maximum-pool-size: 8

logging:
  level:
    root: warn

