server:
  port: 8085
  error:
    whitelabel:
      enabled: false
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 8185
spring:
  main:
    allow-circular-references: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: pedimed
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        order_by:
          default_null_ordering: last
          types:
            print:
              banner: false
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
    hikari:
      pool-name: pedimed
      register-mbeans: true
      maximum-pool-size: 8
  flyway:
    baselineOnMigrate: true
    locations:
      - classpath:/db/migration
  sql:
    init:
      platform: postgresql
logging:
  level:
    root: info
    web: info
    tomcat: info
jwt:
  secret: mySecretKey
  expirationMs: 86400000

---
#################################################################
#                              DEV                              #
#################################################################
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: pedimed-dev
  datasource:
    url: jdbc:postgresql://${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    password: ${DB_PASSWORD_DEV}
    hikari:
      pool-name: pedimed
      register-mbeans: true
      maximum-pool-size: 8
  jpa:
    show-sql: true

logging:
  level:
    root: info
---
#################################################################
#                              PROD                             #
#################################################################
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: pedimed
  flyway:
    user: postgres
    password: postgres
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL_PROD}
    username: ${DB_USERNAME_PROD}
    password: ${DB_PASSWORD_PROD}
    hikari:
      pool-name: pedimed
      register-mbeans: true
      maximum-pool-size: 8

logging:
  level:
    root: warn

