name: CI_MASTER

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
      - name: Set up docker env for testing
        run: docker-compose up -d
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Logging
        run: |
          echo "Deploying Branch : master"
      - name: Deploy on Production
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: 81.241.109.28
          username: joachim18
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          timeout: 60s
          script: |
            echo "DÃ©ploiement en cours..."
            cd /var/www/pedimed/peditrack
            git fetch origin master
            git reset --hard origin/master
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull
            docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
      - name: Check service health
        run: curl -f http://81.241.109.28/health || exit 1
